name: Deploy to EC2 with Docker

on:
  push:
    branches:
      - dev  # Déclenche le workflow uniquement sur les commits de la branche 'dev'

jobs:
  test:
    runs-on: ubuntu-latest  # Utilisation de l'image Ubuntu pour exécuter les étapes

    steps:
      # Checkout du code source depuis le repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Mettre à jour les paquets et installer les dépendances nécessaires
      - name: Update packages and install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y nodejs npm
          npm install

      # Lancer les tests ReactJS
      - name: Run ReactJS tests
        run: |
          npm test -- --maxWorkers=2 --coverage --ci --silent
        continue-on-error: false  # La pipeline s'arrête si les tests échouent
